export const ADAPTER_GRAPH_KEYS = Object.freeze([
  'adapter',
  'anchors',
  'components',
  'diagnostics',
  'header',
  'lossContract',
  'mappings',
  'pipelines',
  'ports',
  'profile',
  'rayEvidence',
  'schemaVersion',
  'segments',
  'sources',
  'supports',
  'topologyHints',
  'units',
]);

export const UXML_REQUIRED_SECTIONS = Object.freeze([
  'header',
  'sources',
  'mappings',
  'units',
  'pipelines',
  'components',
  'anchors',
  'ports',
  'segments',
  'supports',
  'topologyHints',
  'rayEvidence',
  'lossContract',
  'diagnostics',
]);
