import { canonicalStringify,deepFreeze,semanticHash } from '../shared-piping-model/index.js';
import { APPLICATION_NAVIGATION_ORDER_V7,READINESS_STATES,validateWorkspaceConsumerContext,validateWorkspaceConsumerReadinessShape,validateWorkspaceConsumerRegistry } from '../workspace-consumers/index.js';
import { WORKSPACE_HOME_APPLICATION_TITLE,WORKSPACE_HOME_SOURCE_SCHEMA } from './constants.js';
export function createWorkspaceHomeSource(input={}){const{registry,context,readiness}=input;assertInput(registry,context,readiness);const descriptors=new Map(registry.consumers.map((r)=>[r.consumerId,r])),byId=new Map(readiness.map((r)=>[r.consumerId,r])),tabs=APPLICATION_NAVIGATION_ORDER_V7.map((id)=>tabSource(descriptors.get(id),byId.get(id))),base={schema:WORKSPACE_HOME_SOURCE_SCHEMA,applicationTitle:WORKSPACE_HOME_APPLICATION_TITLE,datasetStatus:context.datasetId?'READY':'EMPTY',datasetId:context.datasetId,tabs};return deepFreeze({...base,semanticHash:semanticHash(base)})}
export function validateWorkspaceHomeSource(value){const errors=[];if(value?.schema!==WORKSPACE_HOME_SOURCE_SCHEMA)errors.push('Invalid Workspace Home source schema.');if(value?.applicationTitle!==WORKSPACE_HOME_APPLICATION_TITLE)errors.push('Workspace Home application title is invalid.');if(!['EMPTY','READY'].includes(value?.datasetStatus))errors.push('Workspace Home dataset status is invalid.');if(value?.datasetId!==null&&(typeof value.datasetId!=='string'||!value.datasetId.trim()))errors.push('Workspace Home dataset identity is invalid.');if((value?.datasetStatus==='READY')!==Boolean(value?.datasetId))errors.push('Workspace Home dataset status does not match its identity.');validateTabs(value?.tabs,errors);if(value?.semanticHash!==semanticHash(withoutHash(value)))errors.push('Workspace Home source semantic hash mismatch.');return deepFreeze({ok:!errors.length,errors})}
function assertInput(registry,context,readiness){const rv=validateWorkspaceConsumerRegistry(registry);if(!rv.ok||registry.consumers?.length!==APPLICATION_NAVIGATION_ORDER_V7.length)throw new TypeError('Workspace Home requires a supported 11-tab registry.');const ids=registry.consumers.map((r)=>r.consumerId);if(APPLICATION_NAVIGATION_ORDER_V7.some((id)=>!ids.includes(id)))throw new TypeError('Workspace Home registry identities are incomplete.');const cv=validateWorkspaceConsumerContext(context);if(!cv.ok)throw new TypeError(`Workspace Home context is invalid: ${cv.errors.join(' ')}`);if(!Array.isArray(readiness)||readiness.length!==APPLICATION_NAVIGATION_ORDER_V7.length)throw new TypeError('Workspace Home requires readiness for all application tabs.');const rids=readiness.map((r)=>r?.consumerId);if(new Set(rids).size!==APPLICATION_NAVIGATION_ORDER_V7.length||APPLICATION_NAVIGATION_ORDER_V7.some((id)=>!rids.includes(id)))throw new TypeError('Workspace Home readiness identities are incomplete.');readiness.forEach((r)=>{const v=validateWorkspaceConsumerReadinessShape(r);if(!v.ok)throw new TypeError(`Workspace Home readiness ${r?.consumerId||''} is invalid: ${v.errors.join(' ')}`);if(r.contextSemanticHash!==context.semanticHash)throw new TypeError('Workspace Home readiness must reference the current consumer context.')})}
function tabSource(d,r){if(!d||!r)throw new TypeError('Workspace Home tab evidence is incomplete.');const diagnostic=r.diagnostics[0]||null;return deepFreeze({consumerId:d.consumerId,label:d.label,purpose:d.purpose,implementationStatus:d.implementationStatus,readinessState:r.readinessState,available:r.readinessState===READINESS_STATES.AVAILABLE,diagnosticCode:diagnostic?.code||null,diagnosticMessage:diagnostic?.message||null})}
function validateTabs(tabs,errors){if(!Array.isArray(tabs)||tabs.length!==APPLICATION_NAVIGATION_ORDER_V7.length){errors.push('Workspace Home tabs are incomplete.');return}if(canonicalStringify(tabs.map((r)=>r?.consumerId))!==canonicalStringify(APPLICATION_NAVIGATION_ORDER_V7))errors.push('Workspace Home tab order is invalid.');tabs.forEach((r)=>{if(!r||typeof r.label!=='string'||!r.label||typeof r.purpose!=='string'||!r.purpose)errors.push('Workspace Home tab text is invalid.');if(typeof r?.available!=='boolean')errors.push('Workspace Home tab availability is invalid.');if(r?.available!==(r?.readinessState===READINESS_STATES.AVAILABLE))errors.push('Workspace Home tab availability does not match readiness.');if(r?.diagnosticCode!==null&&(typeof r.diagnosticCode!=='string'||!r.diagnosticCode))errors.push('Workspace Home tab diagnostic code is invalid.');if(r?.diagnosticMessage!==null&&(typeof r.diagnosticMessage!=='string'||!r.diagnosticMessage))errors.push('Workspace Home tab diagnostic message is invalid.')})}
function withoutHash(v){const{semanticHash:_h,...b}=v||{};return b}
