import { buildMasterDbGovernanceSummary } from '../../core/engineering-data/validateMasterDbGovernance.js';

export const REPORT_3D_SIMPLIFIED_SCHEMA_VERSION = 'report-3d-simplified-v19d';
function fmt(value, digits = 2) { const n = Number(value); return Number.isFinite(n) ? n.toFixed(digits) : '—'; }
function collectDiagnostics(...items) { const out = []; for (const item of items) { if (!item) continue; if (Array.isArray(item)) out.push(...item); else if (Array.isArray(item.diagnostics)) out.push(...item.diagnostics); } return out; }
function buildIssueBlockers({ model, issueType, diagnostics, supportLoadResult, forceActionResult, guidedCantileverThermalResult, masterDbGovernance }) {
  const blockers = [];
  if (!model || !Array.isArray(model.segments) || model.segments.length === 0) blockers.push({ code: 'MODEL_MISSING_OR_EMPTY', message: 'A 3D calculation model with at least one segment is required before issuing a report.' });
  if (issueType === 'FINAL_ISSUE') blockers.push({ code: 'FINAL_ISSUE_BLOCKED_SCREENING_METHOD', message: '3D Simplified Calculation is screening-level and cannot be issued as final stress analysis.' });
  for (const item of diagnostics || []) if (item.severity === 'error') blockers.push({ code: item.code || 'DIAGNOSTIC_ERROR', message: item.message || 'Diagnostic error.', data: item.data || {} });
  for (const [label, result] of [['support load', supportLoadResult], ['force action', forceActionResult], ['guided-cantilever thermal', guidedCantileverThermalResult]]) if (result?.status === 'NOT_QUALIFIED') blockers.push({ code: 'CALCULATION_NOT_QUALIFIED', message: `${label} calculation is not qualified.` });
  blockers.push(...(masterDbGovernance?.blockers || []));
  return blockers;
}
function summarizePipeSegments(model = {}) {
  return (model.segments || []).filter((segment) => String(segment.type || segment.properties?.type || 'PIPE').toUpperCase() === 'PIPE').map((segment) => ({ id: segment.id, from: segment.startNode, to: segment.endNode, dn: segment.pipe?.dn ?? segment.properties?.bore ?? null, ratingClass: segment.lineClass?.ratingClass ?? segment.properties?.ratingClass ?? null, faceType: segment.lineClass?.faceType ?? segment.properties?.faceType ?? null, flangeType: segment.lineClass?.flangeType ?? segment.properties?.flangeType ?? null, schedule: segment.pipe?.schedule ?? segment.properties?.schedule ?? null, wall_mm: segment.pipe?.wall_mm ?? segment.properties?.wt ?? null, designTemperature_C: segment.operating?.designTemperature_C ?? segment.properties?.designTemperature_C ?? null, designPressure_barg: segment.operating?.designPressure_barg ?? segment.properties?.designPressure_barg ?? null, fluidDensity_kg_m3: segment.contents?.fluidDensity_kg_m3 ?? segment.properties?.fluidDensity_kg_m3 ?? null, insulationThickness_mm: segment.insulation?.thickness_mm ?? segment.properties?.insulation ?? null }));
}
function summarizeComponents(model = {}) { return Object.values(model.components || {}).map((component) => ({ id: component.id, type: component.type, length_mm: component.length_mm ?? component.totalLength_mm ?? null, weight_kg: component.weight_kg ?? component.totalWeight_kg ?? null, sourceStatus: component.sourceStatus ?? component.dataStatus ?? 'UNKNOWN', fittingDimensionSource: component.fittingDimensionSource || component.flangeDimensionSource || null, fittingDimensionStatus: component.fittingDimensionStatus || component.flangeDimensionStatus || null })); }
export function build3DSimplifiedCalculationReport({ model = null, supportLoadResult = null, forceActionResult = null, guidedCantileverThermalResult = null, suiteResult = null, issueType = 'SCREENING_ISSUE' } = {}) {
  const masterDbGovernance = buildMasterDbGovernanceSummary({ model, issueType, validateWholeDb: issueType === 'FINAL_ISSUE' });
  const diagnostics = collectDiagnostics(model?.diagnostics || [], supportLoadResult, forceActionResult, guidedCantileverThermalResult, suiteResult, masterDbGovernance.diagnostics || []);
  const blockers = buildIssueBlockers({ model, issueType, diagnostics, supportLoadResult, forceActionResult, guidedCantileverThermalResult, masterDbGovernance });
  const report = { schemaVersion: REPORT_3D_SIMPLIFIED_SCHEMA_VERSION, issueType, status: blockers.length ? 'BLOCKED' : 'PASSED', generatedAt: new Date(0).toISOString(), modelSummary: { nodeCount: Object.keys(model?.nodes || {}).length, segmentCount: model?.segments?.length || 0, componentCount: Object.keys(model?.components || {}).length, supportCount: model?.supports?.length || 0 }, pipeSegments: summarizePipeSegments(model || {}), components: summarizeComponents(model || {}), masterDbGovernance, calculations: { supportLoadResult, forceActionResult, guidedCantileverThermalResult, suiteResult }, diagnostics, blockers, assumptions: ['3D Simplified Calculation is screening-level and does not replace detailed code-compliance stress analysis.', 'Seed master-data rows are screening only until replaced by verified project/standard data.'] };
  return { ...report, markdown: export3DSimplifiedReportMarkdown(report), html: export3DSimplifiedReportHtml(report) };
}
export function export3DSimplifiedReportJson(report) { return JSON.stringify(report, null, 2); }
export function export3DSimplifiedReportMarkdown(report) {
  const lines = ['# 3D Simplified Calculation Report', '', `Issue type: ${report.issueType}`, `Status: ${report.status}`, '', '## 1. Model Summary', `Nodes: ${report.modelSummary.nodeCount}`, `Segments: ${report.modelSummary.segmentCount}`, `Components: ${report.modelSummary.componentCount}`, `Supports: ${report.modelSummary.supportCount}`, '', '## 2. Pipe Input Summary', '| ID | From | To | DN | Class | Face | Flange | Sch | WT mm | Temp °C | Press barg | Fluid kg/m³ | Insul mm |', '|---|---|---|---:|---|---|---|---|---:|---:|---:|---:|---:|'];
  for (const seg of report.pipeSegments || []) lines.push(`| ${seg.id} | ${seg.from} | ${seg.to} | ${seg.dn ?? '—'} | CL${seg.ratingClass ?? '—'} | ${seg.faceType ?? '—'} | ${seg.flangeType ?? '—'} | ${seg.schedule ?? '—'} | ${fmt(seg.wall_mm)} | ${fmt(seg.designTemperature_C)} | ${fmt(seg.designPressure_barg)} | ${fmt(seg.fluidDensity_kg_m3)} | ${fmt(seg.insulationThickness_mm)} |`);
  lines.push('', '## 3. Master DB Governance', `Status: ${report.masterDbGovernance?.status || 'NOT_RUN'}`, `Component weight rows: ${report.masterDbGovernance?.counts?.componentWeightRows ?? '—'}`, `Flange dimension rows: ${report.masterDbGovernance?.counts?.flangeDimensionalRows ?? '—'}`, `B16.9 fitting rows: ${report.masterDbGovernance?.counts?.b169FittingRows ?? '—'}`, '', '## 4. Issue Blockers');
  if (report.blockers?.length) for (const blocker of report.blockers) lines.push(`- **${blocker.code}:** ${blocker.message}`); else lines.push('No issue blockers.');
  lines.push('', '## 5. Assumptions'); for (const assumption of report.assumptions || []) lines.push(`- ${assumption}`); lines.push('');
  return lines.join('\n');
}
export function export3DSimplifiedReportHtml(report) { const md = report.markdown || export3DSimplifiedReportMarkdown(report); return `<html><body><pre>${md.replace(/[&<>]/g, (ch) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[ch]))}</pre></body></html>`; }
