export const VERTICAL_LOAD_PATH_PROFILE_SCHEMA = 'vertical-load-path-profile/v1';
export const VERTICAL_LOAD_PATH_MODEL_SCHEMA = 'vertical-load-path-model/v1';
export const TRIBUTARY_SCREENING_SCHEMA = 'tributary-support-load-screening/v1';
export const SCREENING_AUDIT_SCHEMA = 'support-load-screening-audit/v1';
export const PROFILE_ID = 'SIMPLE_CHAIN_TRIBUTARY_VERTICAL_V1';
export const PROFILE_VERSION = 1;

export const PRIMITIVE_TYPES = Object.freeze({
  DISTRIBUTED: 'DISTRIBUTED_GRAVITY_LOAD',
  POINT: 'POINT_GRAVITY_LOAD',
  MOMENT: 'EXPLICIT_POINT_MOMENT',
});

export const FORMULA_IDS = Object.freeze({
  POINT: 'SIMPLE_SPAN_POINT_LOAD_REACTION_V1',
  UNIFORM: 'SIMPLE_SPAN_UNIFORM_SEGMENT_REACTION_V1',
  EQUILIBRIUM: 'SUPPORT_FORCE_EQUILIBRIUM_CHECK_V1',
});

export const QUALIFICATION = Object.freeze({ READY: 'READY', BLOCKED: 'BLOCKED' });

export const AUDIT_CODES = Object.freeze({
  READY: 'READY',
  TOPOLOGY_BRANCH_BLOCKED: 'TOPOLOGY_BRANCH_BLOCKED',
  TOPOLOGY_CYCLE_BLOCKED: 'TOPOLOGY_CYCLE_BLOCKED',
  TOPOLOGY_DISCONNECTED: 'TOPOLOGY_DISCONNECTED',
  PATH_GEOMETRY_BLOCKED: 'PATH_GEOMETRY_BLOCKED',
  INSUFFICIENT_QUALIFIED_SUPPORTS: 'INSUFFICIENT_QUALIFIED_SUPPORTS',
  SUPPORT_UNATTACHED: 'SUPPORT_UNATTACHED',
  SUPPORT_AMBIGUOUS: 'SUPPORT_AMBIGUOUS',
  SUPPORT_PATH_MISMATCH: 'SUPPORT_PATH_MISMATCH',
  SUPPORT_STATION_UNAVAILABLE: 'SUPPORT_STATION_UNAVAILABLE',
  DUPLICATE_SUPPORT_STATION: 'DUPLICATE_SUPPORT_STATION',
  VERTICAL_RESTRAINT_UNRESOLVED: 'VERTICAL_RESTRAINT_UNRESOLVED',
  VERTICAL_GAP_UNSUPPORTED: 'VERTICAL_GAP_UNSUPPORTED',
  VERTICAL_SPRING_UNSUPPORTED: 'VERTICAL_SPRING_UNSUPPORTED',
  LOAD_PRIMITIVE_PATH_MISMATCH: 'LOAD_PRIMITIVE_PATH_MISMATCH',
  POINT_LOAD_STATION_UNAVAILABLE: 'POINT_LOAD_STATION_UNAVAILABLE',
  DISTRIBUTED_LOAD_INTERVAL_UNAVAILABLE: 'DISTRIBUTED_LOAD_INTERVAL_UNAVAILABLE',
  OVERHANG_LOAD_UNSUPPORTED: 'OVERHANG_LOAD_UNSUPPORTED',
  LOAD_CASE_BLOCKED: 'LOAD_CASE_BLOCKED',
  FORCE_EQUILIBRIUM_MISMATCH: 'FORCE_EQUILIBRIUM_MISMATCH',
});
