export const MODEL_SCHEMA = 'local-attachment-foundation-model/v1';
export const RESULT_SCHEMA = 'local-attachment-foundation-result/v1';
export const SOURCE_EVIDENCE_SCHEMA = 'local-attachment-source-evidence/v1';
export const TRANSFORMATION_EVIDENCE_SCHEMA = 'local-attachment-transformation-evidence/v1';
export const QUALIFICATION_PROFILE_SCHEMA = 'local-attachment-qualification-profile/v1';
export const ENGINEERING_LEVEL = 'LOAD_TRANSFER_AND_PRESSURE_BASELINE_ONLY';

export const QUALIFICATION_STATES = Object.freeze({
  ACCEPTED: 'ACCEPTED',
  REJECTED_MODEL: 'REJECTED_MODEL',
  REJECTED_LOAD_CASE: 'REJECTED_LOAD_CASE',
  UNSUPPORTED_REQUEST: 'UNSUPPORTED_REQUEST',
  NUMERICAL_FAILURE: 'NUMERICAL_FAILURE',
});
export const ACTION_SENSES = Object.freeze({
  PIPE_ON_SUPPORT: 'PIPE_ON_SUPPORT',
  SUPPORT_ON_PIPE: 'SUPPORT_ON_PIPE',
});
export const END_CONDITIONS = Object.freeze({
  OPEN_END: 'OPEN_END',
  CLOSED_END: 'CLOSED_END',
  EXPLICIT_AXIAL_RESULTANT: 'EXPLICIT_AXIAL_RESULTANT',
  UNSPECIFIED: 'UNSPECIFIED',
});
export const THICKNESS_POLICIES = Object.freeze({
  NOMINAL_MINUS_CORROSION: 'NOMINAL_MINUS_CORROSION',
  EXPLICIT_ASSESSMENT: 'EXPLICIT_ASSESSMENT',
});
export const REQUEST_TYPES = Object.freeze({
  LOAD_TRANSFER: 'LOAD_TRANSFER',
  PRESSURE_STRESS: 'PRESSURE_STRESS',
});
export const COORDINATE_SYSTEMS = Object.freeze({ GLOBAL: 'GLOBAL', PIPE_LOCAL: 'PIPE_LOCAL' });

export const CANONICAL_UNITS = Object.freeze({
  length: 'mm', force: 'N', moment: 'N·mm', pressure: 'MPa', stress: 'MPa',
});
export const BASE_LIMITATIONS = Object.freeze([
  'NO_LOCAL_ATTACHMENT_STRESS', 'NO_FEA', 'NO_SHELL_BENDING',
  'NO_WELD_STRESS', 'NO_CONTACT', 'NO_CODE_COMPLIANCE',
]);
export const PRESSURE_LIMITATIONS = Object.freeze([
  'ELASTIC_PRESSURE_STRESS_ONLY', 'NO_EXTERNAL_PRESSURE_STABILITY_ASSESSMENT',
]);

export const FORMULA_IDS = Object.freeze({
  BASIS_PROJECTION: 'PIPE_BASIS_PROJECTED_RADIAL_NORMALIZATION_V1',
  GLOBAL_TO_LOCAL: 'GLOBAL_TO_PIPE_LOCAL_ORTHONORMAL_TRANSFORM_V1',
  LOCAL_TO_GLOBAL: 'PIPE_LOCAL_TO_GLOBAL_ORTHONORMAL_RECONSTRUCTION_V1',
  MOMENT_TRANSFER: 'RESULTANT_REFERENCE_POINT_TRANSFER_V1',
  ACTION_REVERSAL: 'ACTION_REACTION_RESULTANT_REVERSAL_V1',
  LAME_A: 'LAME_CYLINDER_A_COEFFICIENT_V1',
  LAME_B: 'LAME_CYLINDER_B_COEFFICIENT_V1',
  RADIAL_STRESS: 'LAME_RADIAL_STRESS_V1',
  HOOP_STRESS: 'LAME_HOOP_STRESS_V1',
  OPEN_END_AXIAL: 'OPEN_END_AXIAL_PRESSURE_STRESS_ZERO_V1',
  CLOSED_END_AXIAL: 'LAME_CLOSED_END_AXIAL_STRESS_V1',
  EXPLICIT_AXIAL: 'EXPLICIT_AXIAL_RESULTANT_SEPARATION_V1',
  FORCE_CONSERVATION: 'FORCE_COMPONENT_RECONSTRUCTION_RESIDUAL_V1',
  MOMENT_CONSERVATION: 'MOMENT_COMMON_ORIGIN_CONSERVATION_RESIDUAL_V1',
  PRESSURE_BOUNDARY: 'LAME_PRESSURE_BOUNDARY_RESIDUAL_V1',
  THIN_WALL_COMPARISON: 'THIN_WALL_HOOP_COMPARISON_NON_AUTHORITATIVE_V1',
});

export const QUALIFICATION_PROFILE = Object.freeze({
  schema: QUALIFICATION_PROFILE_SCHEMA,
  identity: 'LAFEA1_BASELINE_SCALE_AWARE_V1',
  frameMinimumSine: 1e-10,
  handednessMinimumAlignment: 1e-8,
  tolerances: Object.freeze({
    dimensionless: Object.freeze({ absolute: 1e-12, relative: 1e-12 }),
    length: Object.freeze({ absolute: 1e-9, relative: 1e-12 }),
    force: Object.freeze({ absolute: 1e-8, relative: 1e-12 }),
    moment: Object.freeze({ absolute: 1e-5, relative: 1e-12 }),
    stress: Object.freeze({ absolute: 1e-10, relative: 1e-12 }),
  }),
});
