export const LOCAL_STRESS_INPUT_SCHEMA = 'local-stress-foundation-input/v1';
export const LOCAL_STRESS_RESULT_SCHEMA = 'local-stress-foundation-result/v1';
export const ENGINEERING_LEVEL = 'LOAD_TRANSFER_AND_PRESSURE_BASELINE_ONLY';

export const ACTION_SENSES = Object.freeze({
  PIPE_ON_SUPPORT: 'PIPE_ON_SUPPORT',
  SUPPORT_ON_PIPE: 'SUPPORT_ON_PIPE',
});

export const PRESSURE_END_CONDITIONS = Object.freeze({
  OPEN_END: 'OPEN_END',
  CLOSED_END: 'CLOSED_END',
});

export const FORMULA_IDS = Object.freeze({
  BASIS_ORTHOGONALIZATION: 'PIPE_BASIS_PROJECTED_RADIAL_GRAM_SCHMIDT_V1',
  GLOBAL_TO_LOCAL: 'GLOBAL_TO_PIPE_LOCAL_ORTHONORMAL_TRANSFORM_V1',
  MOMENT_TRANSFER: 'RESULTANT_REFERENCE_POINT_TRANSFER_V1',
  LAME_A: 'LAME_CYLINDER_A_COEFFICIENT_V1',
  LAME_B: 'LAME_CYLINDER_B_COEFFICIENT_V1',
  RADIAL_STRESS: 'LAME_RADIAL_STRESS_V1',
  HOOP_STRESS: 'LAME_HOOP_STRESS_V1',
  CLOSED_END_AXIAL: 'LAME_CLOSED_END_AXIAL_STRESS_V1',
});

export const LIMITATIONS = Object.freeze([
  'NO_LOCAL_ATTACHMENT_STRESS',
  'NO_FEA',
  'NO_SHELL_BENDING',
  'NO_WELD_STRESS',
  'NO_CONTACT',
  'NO_CODE_COMPLIANCE',
  'ELASTIC_PRESSURE_STRESS_ONLY',
  'NO_EXTERNAL_PRESSURE_STABILITY_ASSESSMENT',
]);
