import { resolveReducerDimensions, resolveTeeDimensions } from '../../data/b169FittingDimensionalMasterDb.js';
function sourceStatus(status) { return status === 'SCREENING_SAMPLE' ? 'SCREENING_SAMPLE' : status === 'USER_DEFINED' ? 'USER_DEFINED' : ['MISSING_DATA', 'AMBIGUOUS_MATCH'].includes(status) ? 'MISSING_COMPONENT_DATA' : 'VERIFIED'; }
export function resolveReducerComponentData(input = {}) {
  const r = resolveReducerDimensions(input); const v = r.value || {};
  return { moduleId: 'engineering-data', methodId: 'B16_9_REDUCER_DIMENSION_LOOKUP', formulaIds: ['B16_9_REDUCER_END_TO_END_LENGTH_LOOKUP'], isQualified: r.isQualified, status: r.status, sourceStatus: sourceStatus(r.status), value: { fromDn: v.fromDn ?? input.fromDn, toDn: v.toDn ?? input.toDn, reducerType: v.reducerType ?? input.reducerType ?? 'CONCENTRIC', scheduleFrom: v.scheduleFrom ?? input.scheduleFrom ?? 'STD', scheduleTo: v.scheduleTo ?? input.scheduleTo ?? 'STD', length_mm: v.length_mm, weight_kg: v.weight_kg, fittingDimensionSource: v.fittingDimensionSource ?? r.source, fittingDimensionSourceRevision: v.fittingDimensionSourceRevision ?? r.sourceRevision, fittingDimensionStatus: v.fittingDimensionStatus ?? r.status }, source: r.source, sourceRevision: r.sourceRevision, diagnostics: r.diagnostics || [] };
}
export function resolveTeeComponentData(input = {}) {
  const r = resolveTeeDimensions(input); const v = r.value || {};
  return { moduleId: 'engineering-data', methodId: 'B16_9_TEE_DIMENSION_LOOKUP', formulaIds: ['B16_9_TEE_RUN_AND_BRANCH_C2E_LOOKUP'], isQualified: r.isQualified, status: r.status, sourceStatus: sourceStatus(r.status), value: { headerDn: v.headerDn ?? input.headerDn, branchDn: v.branchDn ?? input.branchDn, teeType: v.teeType ?? input.teeType, schedule: v.schedule ?? input.schedule ?? 'STD', runC2E_mm: v.runC2E_mm, branchC2E_mm: v.branchC2E_mm, weight_kg: v.weight_kg, fittingDimensionSource: v.fittingDimensionSource ?? r.source, fittingDimensionSourceRevision: v.fittingDimensionSourceRevision ?? r.sourceRevision, fittingDimensionStatus: v.fittingDimensionStatus ?? r.status }, source: r.source, sourceRevision: r.sourceRevision, diagnostics: r.diagnostics || [] };
}
