export const VERTICAL_BEAM_SOLVER_PROFILE_SCHEMA = 'vertical-beam-solver-profile/v1';
export const FLEXURAL_PROPERTY_PROJECTION_SCHEMA = 'flexural-property-projection/v1';
export const VERTICAL_BEAM_MODEL_SCHEMA = 'vertical-beam-model/v1';
export const VERTICAL_BEAM_SOLUTION_SCHEMA = 'vertical-beam-solution/v1';
export const VERTICAL_BEAM_SOLVER_AUDIT_SCHEMA = 'vertical-beam-solver-audit/v1';
export const PROFILE_ID = 'EULER_BERNOULLI_VERTICAL_PATH_V1';
export const PROFILE_VERSION = '1.0.0';
export const QUALIFICATION = Object.freeze({ READY: 'READY', BLOCKED: 'BLOCKED' });
export const FLEXURAL_BASIS = Object.freeze({
  DIRECT_EI: 'DIRECT_FLEXURAL_RIGIDITY',
  EXPLICIT_E_I: 'EXPLICIT_ELASTIC_MODULUS_X_DIRECT_SECOND_MOMENT',
  CIRCULAR_E_I: 'EXPLICIT_ELASTIC_MODULUS_X_DERIVED_CIRCULAR_SECTION_SECOND_MOMENT',
});
export const FORMULA_IDS = Object.freeze({
  CIRCULAR_I: 'CIRCULAR_HOLLOW_SECTION_SECOND_MOMENT_V1',
  EI_FROM_E_I: 'FLEXURAL_RIGIDITY_FROM_E_AND_I_V1',
  ELEMENT_STIFFNESS: 'EULER_BERNOULLI_ELEMENT_STIFFNESS_V1',
  UNIFORM_LOAD: 'EULER_BERNOULLI_UNIFORM_LOAD_VECTOR_V1',
  POINT_LOAD: 'EULER_BERNOULLI_NODE_POINT_LOAD_V1',
  GLOBAL_ASSEMBLY: 'VERTICAL_BEAM_GLOBAL_ASSEMBLY_V1',
  LINEAR_SOLVE: 'SCALED_PARTIAL_PIVOT_LINEAR_SOLVE_V1',
  FORCE_EQUILIBRIUM: 'VERTICAL_BEAM_FORCE_EQUILIBRIUM_V1',
  MOMENT_EQUILIBRIUM: 'VERTICAL_BEAM_MOMENT_EQUILIBRIUM_V1',
  MATRIX_RESIDUAL: 'VERTICAL_BEAM_MATRIX_RESIDUAL_V1',
});
export const AUDIT_CODES = Object.freeze({
  READY: 'READY', PATH_NOT_QUALIFIED: 'PATH_NOT_QUALIFIED',
  INSUFFICIENT_VERTICAL_SUPPORTS: 'INSUFFICIENT_VERTICAL_SUPPORTS',
  DUPLICATE_SUPPORT_STATION: 'DUPLICATE_SUPPORT_STATION',
  MISSING_FLEXURAL_PROPERTY: 'MISSING_FLEXURAL_PROPERTY',
  INVALID_ELASTIC_MODULUS: 'INVALID_ELASTIC_MODULUS',
  INVALID_SECOND_MOMENT: 'INVALID_SECOND_MOMENT',
  INVALID_FLEXURAL_RIGIDITY: 'INVALID_FLEXURAL_RIGIDITY',
  INVALID_CIRCULAR_SECTION: 'INVALID_CIRCULAR_SECTION',
  UNSUPPORTED_COMPONENT_FLEXURAL_MODEL: 'UNSUPPORTED_COMPONENT_FLEXURAL_MODEL',
  LOAD_CASE_BLOCKED: 'LOAD_CASE_BLOCKED',
  LOAD_PRIMITIVE_PATH_MISMATCH: 'LOAD_PRIMITIVE_PATH_MISMATCH',
  DISTRIBUTED_LOAD_MAPPING_FAILED: 'DISTRIBUTED_LOAD_MAPPING_FAILED',
  POINT_LOAD_MAPPING_FAILED: 'POINT_LOAD_MAPPING_FAILED',
  POINT_MOMENT_UNSUPPORTED: 'POINT_MOMENT_UNSUPPORTED',
  MATRIX_NONFINITE: 'MATRIX_NONFINITE', MATRIX_SINGULAR: 'MATRIX_SINGULAR',
  MATRIX_NEAR_SINGULAR: 'MATRIX_NEAR_SINGULAR',
  MATRIX_RESIDUAL_EXCEEDED: 'MATRIX_RESIDUAL_EXCEEDED',
  SUPPORT_DISPLACEMENT_RESIDUAL: 'SUPPORT_DISPLACEMENT_RESIDUAL',
  FORCE_EQUILIBRIUM_MISMATCH: 'FORCE_EQUILIBRIUM_MISMATCH',
  MOMENT_EQUILIBRIUM_MISMATCH: 'MOMENT_EQUILIBRIUM_MISMATCH',
  SUPPORT_UPLIFT_OR_DIRECTION_REVERSAL: 'SUPPORT_UPLIFT_OR_DIRECTION_REVERSAL',
});
export const ELIGIBLE_CIRCULAR_TYPES = Object.freeze(['PIPE', 'STRAIGHT_PIPE', 'TUBE']);
export const ELIGIBLE_LOAD_TYPES = Object.freeze(['DISTRIBUTED_GRAVITY_LOAD', 'POINT_GRAVITY_LOAD']);
