export const TOPOLOGY_CONNECTION_PROFILE_SCHEMA = 'topology-connection-profile/v1';
export const ENGINEERING_PORT_PROJECTION_SCHEMA = 'engineering-port-projection/v1';
export const PIPING_PORT_TOPOLOGY_GRAPH_SCHEMA = 'piping-port-topology-graph/v1';
export const TOPOLOGY_CONNECTION_AUDIT_SCHEMA = 'topology-connection-audit/v1';

export const TOPOLOGY_EVIDENCE = Object.freeze({
  EXPLICIT_CONNECTION_REFERENCE: 'EXPLICIT_CONNECTION_REFERENCE',
  SHARED_SOURCE_ENDPOINT_IDENTITY: 'SHARED_SOURCE_ENDPOINT_IDENTITY',
  EXACT_COORDINATE: 'EXACT_COORDINATE',
  TOLERANCE_INFERRED: 'TOLERANCE_INFERRED',
});

export const TOPOLOGY_STATES = Object.freeze({
  CONNECTED: 'CONNECTED',
  UNCONNECTED: 'UNCONNECTED',
  AMBIGUOUS: 'AMBIGUOUS',
  IDENTITY_CONFLICT: 'IDENTITY_CONFLICT',
  INVALID_POSITION: 'INVALID_POSITION',
  UNIT_BLOCKED: 'UNIT_BLOCKED',
});

export const EXACT_PROFILE_ID = 'EXACT_ONLY_V1';
export const TOLERANCE_PROFILE_ID = 'TOLERANCE_EXPLICIT_V1';
export const IDENTITY_POLICY = 'STRICT_IDENTITY_COMPATIBILITY_V1';
export const CANONICAL_LENGTH_UNIT = 'mm';
