export function renderWorkspaceLayout(rootElement) {
  rootElement.replaceChildren();
  const shell = rootElement.ownerDocument.createElement('div');
  shell.innerHTML = workspaceMarkup();
  const style = rootElement.ownerDocument.createElement('style');
  style.textContent = shellStyles();
  rootElement.append(style, shell.firstElementChild);
}
function workspaceMarkup() {
  return `<div class="application-shell" data-role="application-shell">
      <header class="application-navigation-shell"><div class="application-navigation" data-role="application-navigation" role="navigation" aria-label="Application views"></div><output class="application-navigation__status" data-role="application-navigation-status" aria-live="polite"></output></header>
      <div class="application-view application-view--home" data-application-view="HOME"><div data-role="home-consumer-root"></div></div>
      <div class="application-view application-view--workspace" data-application-view="WORKSPACE" hidden aria-hidden="true">
    <main class="workspace-shell" aria-label="Analysis Workspace">
      <aside class="workspace-panel tree-panel" data-panel="tree" aria-label="Dataset tree and layers">
        <header class="panel-header"><span class="panel-eyebrow">Analysis Workspace</span><h1>Dataset Tree</h1></header>
        <section class="dataset-toolbar" aria-label="Dataset actions"><div class="dataset-toolbar__actions"><button type="button" data-action="import-dataset">Import JSON</button><button type="button" data-action="clear-dataset" disabled>Clear</button></div><input data-role="dataset-file" type="file" accept=".json,application/json" hidden><output data-role="tree-status">No dataset loaded</output><p class="dataset-error" data-role="tree-error" hidden></p></section>
        <section class="layer-summary" aria-label="Dataset summary"><span data-role="summary-pipes">Pipes 0</span><span data-role="summary-supports">Supports 0</span></section>
        <div class="tree-list" data-role="tree-list"><p class="panel-empty">Import a supported workspace JSON package.</p></div>
      </aside>
      <section class="workspace-panel viewport-panel" data-panel="viewport" aria-label="3D viewport">
        <header class="viewport-toolbar"><div><span class="panel-eyebrow">Read-only model review</span><h2>Model Viewport</h2></div><div class="viewport-toolbar__status"><output data-role="viewport-status">No dataset loaded</output><div class="viewport-toolbar__actions" aria-label="Viewport navigation"><button type="button" data-viewport-action="fit">Fit View</button><button type="button" data-viewport-action="reset">Reset View</button></div></div></header>
        <div class="viewport-stage" data-webgl-host data-role="viewport-render-host" aria-label="Read-only model viewport"></div><footer class="viewport-footer" data-role="viewport-selection">Selection: none</footer>
      </section>
      <aside class="workspace-panel properties-panel" data-panel="properties" aria-label="Properties and analysis actions">
        <header class="panel-header"><span class="panel-eyebrow">Model and contextual workflow</span><h2>Properties &amp; Actions</h2></header>
        <div data-role="shared-model-summary"></div><div data-role="topology-summary"></div><div data-role="support-restraint-summary"></div><div data-role="model-load-summary"></div><div data-role="support-load-screening-summary"></div><div data-role="vertical-beam-summary"></div><div data-role="model-calculation-summary"></div><div data-role="model-support-load-summary"></div>
        <div class="properties-content" data-role="properties-content"><p class="panel-empty">Select an entity to inspect its properties.</p></div>
      </aside>
    </main></div>
      <div class="application-view application-view--load-calc" data-application-view="LOAD_CALC" hidden aria-hidden="true"><div data-role="load-calc-consumer-root"></div></div>
      <div class="application-view application-view--pcf" data-application-view="PCF" hidden aria-hidden="true"><div data-role="pcf-consumer-root"></div></div>
      <div class="application-view application-view--sketcher" data-application-view="SKETCHER" hidden aria-hidden="true">${unavailableView('Sketcher','Sketcher capability has not yet been migrated to the current runtime.')}</div>
      <div class="application-view application-view--three-d-calc" data-application-view="THREE_D_CALC" hidden aria-hidden="true"><div data-role="three-d-calc-consumer-root"></div></div>
      <div class="application-view application-view--pipe-solver" data-application-view="PIPE_SOLVER" hidden aria-hidden="true"><div data-role="pipe-solver-consumer-root"></div></div>
      <div class="application-view application-view--reports" data-application-view="REPORTS" hidden aria-hidden="true"><div data-role="reports-consumer-root"></div></div>
      <div class="application-view application-view--qa" data-application-view="QA" hidden aria-hidden="true">${unavailableView('QA','QA is not implemented in the current runtime.')}</div>
      <div class="application-view application-view--settings" data-application-view="SETTINGS" hidden aria-hidden="true">${unavailableView('Settings','Settings authority has not yet been migrated to the current runtime.')}</div>
      <div class="application-view application-view--debug" data-application-view="DEBUG" hidden aria-hidden="true">${unavailableView('Debug','Debug is not implemented in the current runtime.')}</div>
    </div>`;
}
function unavailableView(title, message) { return `<section class="unavailable-view"><h1>${title}</h1><p>${message}</p></section>`; }
function shellStyles() {
  return `
    .application-shell{display:grid;grid-template-rows:auto minmax(0,1fr);height:100vh;min-width:0;overflow:hidden;background:var(--workspace-canvas);color:var(--workspace-text)}
    .application-navigation-shell{display:grid;border-bottom:1px solid var(--workspace-border);background:var(--workspace-panel-strong)}
    .application-navigation{display:flex;align-items:center;gap:6px;min-width:0;padding:8px 12px 4px;overflow-x:auto}.application-navigation__status{min-height:20px;padding:0 12px 6px;color:#fca5a5;font-size:12px}
    .application-navigation__item{min-width:0}.application-navigation button{border:1px solid #334155;border-radius:5px;padding:7px 11px;background:#0b1628;color:var(--workspace-text);font-weight:700;white-space:nowrap;cursor:pointer}.application-navigation button:hover,.application-navigation button:focus-visible{border-color:var(--workspace-accent);outline:2px solid rgba(96,165,250,.45);outline-offset:2px}.application-navigation button[aria-disabled="true"]{color:#94a3b8;cursor:help}.application-navigation__button--active{border-color:#fbbf24!important;background:#1d2433!important;color:#fde68a!important}
    .application-navigation__reason[hidden]{display:none}.application-navigation__reason{display:block;max-width:180px;padding-top:4px;color:#cbd5e1;font-size:10px}
    .application-view{min-width:0;min-height:0;overflow:hidden}.application-view[hidden]{display:none!important}.application-view--workspace .workspace-shell{height:100%}
    .application-view--home,.application-view--reports,.application-view--load-calc,.application-view--pcf,.application-view--three-d-calc,.application-view--pipe-solver{overflow:auto;background:var(--workspace-canvas)}
    .home-consumer,.reports-consumer,.load-calc-consumer,.pcf-consumer,.three-d-calc-consumer,.pipe-solver-consumer{display:grid;gap:14px;max-width:1500px;margin:0 auto;padding:18px;min-width:0}
    .home-consumer__header,.reports-consumer__header,.load-calc-consumer__header,.pcf-consumer__header,.three-d-calc-consumer__header,.pipe-solver-consumer__header{display:flex;align-items:flex-start;justify-content:space-between;gap:20px}.home-consumer__header h1,.reports-consumer__header h1,.load-calc-consumer__header h1,.pcf-consumer__header h1,.three-d-calc-consumer__header h1,.pipe-solver-consumer__header h1{margin:4px 0 0}
    .home-consumer__header p,.pcf-consumer__claim,.reports-consumer__disclaimer,.reports-consumer__footer,.load-calc-consumer__claim,.three-d-calc-consumer__claim,.pipe-solver-consumer__claim{max-width:620px;color:#fbbf24;font-weight:700}
    .home-card,.reports-card,.load-calc-card,.pcf-card,.three-d-calc-card,.pipe-solver-card{min-width:0;padding:14px;border:1px solid var(--workspace-border);border-radius:7px;background:var(--workspace-panel)}.home-card h2,.reports-card h2,.load-calc-card h2,.pcf-card h2,.three-d-calc-card h2,.pipe-solver-card h2{margin:0 0 10px;font-size:14px}
    .home-card dl,.reports-card dl,.load-calc-card dl,.pcf-card dl,.three-d-calc-card dl,.pipe-solver-card dl{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin:0}.home-card dl div,.reports-card dl div,.load-calc-card dl div,.pcf-card dl div,.three-d-calc-card dl div,.pipe-solver-card dl div{min-width:0;padding:8px;background:#060b14}.home-card dt,.reports-card dt,.load-calc-card dt,.pcf-card dt,.three-d-calc-card dt,.pipe-solver-card dt{color:var(--workspace-muted);font-size:11px}.home-card dd,.reports-card dd,.load-calc-card dd,.pcf-card dd,.three-d-calc-card dd,.pipe-solver-card dd{margin:4px 0 0;overflow-wrap:anywhere;font-weight:700}
    .home-consumer__actions,.pcf-consumer__actions{display:flex;flex-wrap:wrap;gap:8px}.home-consumer__actions button,.pcf-consumer button,.pcf-consumer input,.pcf-consumer textarea{border:1px solid #334155;border-radius:5px;padding:8px;background:#0b1628;color:var(--workspace-text)}.home-consumer__actions button:focus-visible,.pcf-consumer button:focus-visible,.pcf-consumer input:focus-visible,.pcf-consumer textarea:focus-visible{outline:2px solid rgba(96,165,250,.55);outline-offset:2px}.pcf-consumer button:disabled{color:#94a3b8;cursor:not-allowed}.pcf-consumer__file{display:grid;gap:6px}.pcf-consumer textarea{box-sizing:border-box;width:100%;min-height:240px;resize:vertical;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.pcf-consumer__status{display:block;min-height:22px;color:#bfdbfe}.pcf-consumer__table-wrap{max-width:100%;overflow:auto}.pcf-consumer table{width:100%;border-collapse:collapse;font-size:12px}.pcf-consumer th,.pcf-consumer td{padding:8px;border-bottom:1px solid var(--workspace-border);text-align:left;vertical-align:top;overflow-wrap:anywhere}.pcf-consumer th{color:#bfdbfe;white-space:nowrap}.pcf-consumer pre{max-width:520px;white-space:pre-wrap;overflow-wrap:anywhere}
    .home-consumer__loading{padding:20px;color:var(--workspace-muted)}.unavailable-view{max-width:760px;margin:40px auto;padding:20px;border:1px solid var(--workspace-border);border-radius:7px;background:var(--workspace-panel)}
    .reports-consumer__controls,.load-calc-consumer__controls,.three-d-calc-consumer__controls,.pipe-solver-consumer__controls{display:flex;flex-wrap:wrap;align-items:end;gap:8px;padding:12px;border:1px solid var(--workspace-border);border-radius:7px;background:var(--workspace-panel)}.reports-consumer__controls label,.pipe-solver-consumer__controls label{display:grid;gap:5px;min-width:220px;color:var(--workspace-muted);font-size:11px}.reports-consumer__controls select,.reports-consumer__controls button,.load-calc-consumer__controls button,.three-d-calc-consumer__controls button,.pipe-solver-consumer__controls button,.pipe-solver-consumer__controls select{border:1px solid #334155;border-radius:5px;padding:8px;background:#0b1628;color:var(--workspace-text)}
    .load-calc-consumer__controls button[aria-disabled="true"],.three-d-calc-consumer__controls button[aria-disabled="true"],.pipe-solver-consumer__controls button[aria-disabled="true"]{color:#94a3b8;cursor:not-allowed}.reports-consumer__controls output,.load-calc-consumer__controls output,.three-d-calc-consumer__controls output,.pipe-solver-consumer__controls output{flex-basis:100%;color:#bfdbfe}
    .reports-table-wrap,.load-calc-table-wrap,.three-d-calc-table-wrap,.pipe-solver-table-wrap{max-width:100%;overflow:auto}.reports-card table,.load-calc-card table,.three-d-calc-card table,.pipe-solver-card table{width:100%;border-collapse:collapse;font-size:12px}.reports-card th,.reports-card td,.load-calc-card th,.load-calc-card td,.three-d-calc-card th,.three-d-calc-card td,.pipe-solver-card th,.pipe-solver-card td{padding:8px;border-bottom:1px solid var(--workspace-border);text-align:left;vertical-align:top;overflow-wrap:anywhere}.reports-card th,.load-calc-card th,.three-d-calc-card th,.pipe-solver-card th{color:#bfdbfe;white-space:nowrap}.load-calc-card code,.three-d-calc-card code,.pipe-solver-card code,.pipe-solver-card pre{white-space:pre-wrap;overflow-wrap:anywhere}.pipe-solver-card input{min-width:130px;border:1px solid #334155;border-radius:4px;padding:6px;background:#060b14;color:var(--workspace-text)}.pipe-solver-ledger-row--active{background:#1d2433}
    .visually-hidden{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
    @media(max-width:1100px){.application-navigation{flex-wrap:wrap;overflow-x:visible}.home-card dl,.reports-card dl,.load-calc-card dl,.pcf-card dl,.three-d-calc-card dl,.pipe-solver-card dl{grid-template-columns:repeat(2,minmax(0,1fr))}}
    @media(max-width:760px){.application-shell{height:auto;min-height:100vh;overflow:visible}.application-view{overflow:visible}.application-view--workspace .workspace-shell{height:auto}.home-consumer__header,.reports-consumer__header,.load-calc-consumer__header,.pcf-consumer__header,.three-d-calc-consumer__header,.pipe-solver-consumer__header{display:grid}.home-card dl,.reports-card dl,.load-calc-card dl,.pcf-card dl,.three-d-calc-card dl,.pipe-solver-card dl{grid-template-columns:minmax(0,1fr)}}`;
}
