import { canonicalStringify,deepFreeze,semanticHash } from '../shared-piping-model/index.js';
import { IMPLEMENTATION_STATUS,READINESS_STATES,WORKSPACE_CONSUMER_READINESS_SCHEMA } from './constants.js';
import { validateWorkspaceConsumerContext } from './context.js';
import { validateWorkspaceConsumerRegistry,workspaceConsumerDescriptor } from './registry.js';
export function createWorkspaceConsumerReadiness(registry,context,consumerId,options={}){const descriptor=workspaceConsumerDescriptor(registry,consumerId),available=new Set(context?.availabilitySummary?.availableContractKeys||[]),invalid=new Set(context?.availabilitySummary?.invalidContractKeys||[]),required=descriptor.requiredContractKeys,declared=[...new Set([...required,...descriptor.optionalContractKeys])].sort(),invalidRequired=required.filter((k)=>invalid.has(k)).sort(),missingRequired=required.filter((k)=>!available.has(k)&&!invalid.has(k)).sort(),readinessState=stateFor(descriptor,invalidRequired,missingRequired,options);const base={schema:WORKSPACE_CONSUMER_READINESS_SCHEMA,consumerId,implementationStatus:descriptor.implementationStatus,readinessState,availableContractKeys:declared.filter((k)=>available.has(k)),missingRequiredContractKeys:missingRequired,invalidContractKeys:declared.filter((k)=>invalid.has(k)),blockers:blockersFor(readinessState,invalidRequired,missingRequired,consumerId,options),diagnostics:diagnosticsFor(readinessState,invalidRequired,missingRequired,descriptor.label,consumerId,options),contextSemanticHash:context?.semanticHash||null};return deepFreeze({...base,semanticHash:semanticHash(base)})}
export function validateWorkspaceConsumerReadiness(value,registry,context,options={}){const errors=validateWorkspaceConsumerReadinessShape(value).errors.slice();if(!validateWorkspaceConsumerRegistry(registry).ok)errors.push('Workspace consumer readiness registry is invalid.');if(!validateWorkspaceConsumerContext(context).ok)errors.push('Workspace consumer readiness context is invalid.');if(!errors.length){try{const expected=createWorkspaceConsumerReadiness(registry,context,value.consumerId,options);if(canonicalStringify(value)!==canonicalStringify(expected))errors.push('Workspace consumer readiness does not match registry and context evidence.')}catch(error){errors.push(error.message)}}return deepFreeze({ok:!errors.length,errors})}
export function validateWorkspaceConsumerReadinessShape(value){const errors=[];if(value?.schema!==WORKSPACE_CONSUMER_READINESS_SCHEMA)errors.push('Invalid workspace consumer readiness schema.');if(typeof value?.consumerId!=='string'||!value.consumerId)errors.push('Workspace consumer readiness consumerId is invalid.');if(!Object.values(IMPLEMENTATION_STATUS).includes(value?.implementationStatus))errors.push('Workspace consumer implementation status is invalid.');if(!Object.values(READINESS_STATES).includes(value?.readinessState))errors.push('Workspace consumer readiness state is invalid.');if(typeof value?.contextSemanticHash!=='string'||!value.contextSemanticHash.trim())errors.push('Workspace consumer readiness contextSemanticHash is invalid.');['availableContractKeys','missingRequiredContractKeys','invalidContractKeys','blockers'].forEach((f)=>validateCanonicalStringArray(value?.[f],f,errors));validateDiagnosticArray(value?.diagnostics,errors);validateLogicalState(value,errors);if(value?.semanticHash!==semanticHash(withoutHash(value)))errors.push('Workspace consumer readiness semantic hash mismatch.');return deepFreeze({ok:!errors.length,errors})}
export function createWorkspaceConsumerReadinessRegistry(registry,context,options={}){return deepFreeze(registry.consumers.map((r)=>createWorkspaceConsumerReadiness(registry,context,r.consumerId,options)).sort((a,b)=>a.consumerId.localeCompare(b.consumerId)))}
function stateFor(d,invalid,missing,o){if(d.implementationStatus===IMPLEMENTATION_STATUS.RECOVERY_PENDING)return READINESS_STATES.RECOVERY_PENDING;if(d.implementationStatus===IMPLEMENTATION_STATUS.NOT_IMPLEMENTED)return READINESS_STATES.NOT_IMPLEMENTED;if(d.consumerId==='WORKSPACE'&&o.workspaceBooted!==true)return READINESS_STATES.BLOCKED_MISSING_CONTRACTS;if(d.consumerId==='SETTINGS'&&!(o.settingsAuthorityInitialized&&o.settingsDefinitionsAvailable&&o.settingsProfileValid))return READINESS_STATES.BLOCKED_MISSING_CONTRACTS;if(invalid.length)return READINESS_STATES.BLOCKED_INVALID_CONTRACTS;if(missing.length)return READINESS_STATES.BLOCKED_MISSING_CONTRACTS;return READINESS_STATES.AVAILABLE}
function blockersFor(state,invalid,missing,id,o){if(state===READINESS_STATES.RECOVERY_PENDING)return['VIEW_RECOVERY_PENDING'];if(state===READINESS_STATES.NOT_IMPLEMENTED)return['CONSUMER_NOT_IMPLEMENTED'];if(state===READINESS_STATES.BLOCKED_INVALID_CONTRACTS)return invalid.map((k)=>`INVALID_CONTRACT:${k}`);if(state===READINESS_STATES.BLOCKED_MISSING_CONTRACTS){if(id==='SETTINGS')return settingsBlockers(o);return missing.length?missing.map((k)=>`MISSING_CONTRACT:${k}`):['WORKSPACE_NOT_BOOTED']}return[]}
function settingsBlockers(o){const rows=[];if(!o.settingsAuthorityInitialized)rows.push('SETTINGS_AUTHORITY_NOT_INITIALIZED');if(!o.settingsDefinitionsAvailable)rows.push('SETTINGS_DEFINITIONS_UNAVAILABLE');if(!o.settingsProfileValid)rows.push('SETTINGS_PROFILE_INVALID');return rows.sort()}
function diagnosticsFor(state,invalid,missing,label,id,o){if(state===READINESS_STATES.RECOVERY_PENDING)return[diagnostic('VIEW_RECOVERY_PENDING',`${label} is visible for recovery tracking but is not yet migrated to the current runtime.`)];if(state===READINESS_STATES.NOT_IMPLEMENTED)return[diagnostic('CONSUMER_NOT_IMPLEMENTED',`${label} is not implemented in the current runtime.`)];if(state===READINESS_STATES.BLOCKED_INVALID_CONTRACTS)return invalid.map((k)=>diagnostic('INVALID_REQUIRED_CONTRACT',`Required contract ${k} is invalid or stale.`,k));if(state===READINESS_STATES.BLOCKED_MISSING_CONTRACTS){if(id==='SETTINGS')return settingsBlockers(o).map((code)=>diagnostic(code,settingsMessage(code)));return missing.length?missing.map((k)=>diagnostic('MISSING_REQUIRED_CONTRACT',`Required contract ${k} is unavailable.`,k)):[diagnostic('WORKSPACE_NOT_BOOTED','The current Workspace shell is not booted.')]}return[]}
function settingsMessage(code){return({SETTINGS_AUTHORITY_NOT_INITIALIZED:'The current settings authority is not initialized.',SETTINGS_DEFINITIONS_UNAVAILABLE:'Approved setting definitions are unavailable.',SETTINGS_PROFILE_INVALID:'No valid active engineering settings profile is available.'})[code]}
function validateLogicalState(v,e){const s=v?.readinessState;if(v?.implementationStatus===IMPLEMENTATION_STATUS.RECOVERY_PENDING&&s!==READINESS_STATES.RECOVERY_PENDING)e.push('A recovery-pending consumer must remain RECOVERY_PENDING.');if(v?.implementationStatus===IMPLEMENTATION_STATUS.NOT_IMPLEMENTED&&s!==READINESS_STATES.NOT_IMPLEMENTED)e.push('A non-implemented consumer must remain NOT_IMPLEMENTED.');if(v?.implementationStatus===IMPLEMENTATION_STATUS.IMPLEMENTED&&[READINESS_STATES.RECOVERY_PENDING,READINESS_STATES.NOT_IMPLEMENTED].includes(s))e.push('An implemented consumer cannot report a non-runtime readiness state.');if(s===READINESS_STATES.AVAILABLE&&(v?.missingRequiredContractKeys?.length||v?.blockers?.length||v?.diagnostics?.length))e.push('AVAILABLE readiness contains blockers.');if(s===READINESS_STATES.RECOVERY_PENDING&&canonicalStringify(v?.blockers)!==canonicalStringify(['VIEW_RECOVERY_PENDING']))e.push('RECOVERY_PENDING readiness blockers are inconsistent.');if(s===READINESS_STATES.NOT_IMPLEMENTED&&canonicalStringify(v?.blockers)!==canonicalStringify(['CONSUMER_NOT_IMPLEMENTED']))e.push('NOT_IMPLEMENTED readiness blockers are inconsistent.');if(s===READINESS_STATES.BLOCKED_INVALID_CONTRACTS&&!v?.invalidContractKeys?.length)e.push('Invalid-contract readiness has no invalid contract.')}
function validateCanonicalStringArray(v,f,e){if(!Array.isArray(v)||v.some((r)=>typeof r!=='string')){e.push(`Workspace consumer readiness ${f} is invalid.`);return}if(canonicalStringify(v)!==canonicalStringify([...new Set(v)].sort()))e.push(`Workspace consumer readiness ${f} is not canonical.`)}
function validateDiagnosticArray(v,e){if(!Array.isArray(v)){e.push('Workspace consumer readiness diagnostics is invalid.');return}const keys=v.map((r)=>`${r?.code}|${r?.contractKey||''}|${r?.message||''}`);if(canonicalStringify(keys)!==canonicalStringify([...new Set(keys)].sort()))e.push('Workspace consumer readiness diagnostics are not canonical.');v.forEach((r)=>{if(!r||r.severity!=='INFO'||typeof r.code!=='string'||!r.code||typeof r.message!=='string'||!r.message)e.push('Workspace consumer readiness diagnostic is invalid.')})}
function diagnostic(code,message,contractKey=null){return deepFreeze({code,severity:'INFO',contractKey,message})}
function withoutHash(v){const{semanticHash:_h,...b}=v||{};return b}
