export const SUPPORT_ATTACHMENT_PROFILE_SCHEMA = 'support-attachment-profile/v1';
export const ENGINEERING_SUPPORT_PROJECTION_SCHEMA = 'engineering-support-projection/v1';
export const SUPPORT_ATTACHMENT_MODEL_SCHEMA = 'support-attachment-model/v1';
export const SUPPORT_ATTACHMENT_AUDIT_SCHEMA = 'support-attachment-audit/v1';
export const RESTRAINT_CLASSIFICATION_PROFILE_SCHEMA = 'restraint-classification-profile/v1';
export const RESTRAINT_CAPABILITY_MODEL_SCHEMA = 'restraint-capability-model/v1';
export const RESTRAINT_CAPABILITY_AUDIT_SCHEMA = 'restraint-capability-audit/v1';

export const ATTACHMENT_PROFILE_IDS = Object.freeze({
  EVIDENCE_ONLY: 'EVIDENCE_ONLY_V1',
  GEOMETRIC: 'GEOMETRIC_PROJECTION_EXPLICIT_V1',
});

export const ATTACHMENT_EVIDENCE = Object.freeze({
  EXPLICIT_PORT: 'EXPLICIT_ATTACHED_PORT_REFERENCE',
  EXPLICIT_COMPONENT: 'EXPLICIT_ATTACHED_COMPONENT_REFERENCE',
  SOURCE_RELATION: 'UNIQUE_SOURCE_PARENT_OR_PATH_RELATION',
  GEOMETRIC: 'GEOMETRIC_PROJECTION_EXPLICIT',
});

export const ATTACHMENT_STATUS = Object.freeze({
  ATTACHED: 'ATTACHED',
  UNATTACHED: 'UNATTACHED',
  AMBIGUOUS: 'AMBIGUOUS',
  INVALID_SUPPORT_POSITION: 'INVALID_SUPPORT_POSITION',
  INVALID_COMPONENT_GEOMETRY: 'INVALID_COMPONENT_GEOMETRY',
  IDENTITY_CONFLICT: 'IDENTITY_CONFLICT',
  UNIT_BLOCKED: 'UNIT_BLOCKED',
});

export const RESTRAINT_DIRECTIONS = Object.freeze([
  'VERTICAL',
  'LATERAL',
  'LONGITUDINAL',
  'ROTATIONAL',
]);

export const RESTRAINT_STATES = Object.freeze({
  RESTRAINED: 'RESTRAINED',
  FREE: 'FREE',
  GAP: 'GAP',
  SPRING: 'SPRING',
  UNKNOWN: 'UNKNOWN',
  CONFLICT: 'CONFLICT',
});

export const RESTRAINT_QUALIFICATIONS = Object.freeze({
  EXPLICIT: 'EXPLICITLY_RESOLVED',
  TYPE: 'TYPE_CLASSIFIED',
  PARTIAL: 'PARTIALLY_RESOLVED',
  UNRESOLVED: 'UNRESOLVED',
  BLOCKED: 'BLOCKED_ATTACHMENT',
  CONFLICTED: 'CONFLICTED',
});

export const RESTRAINT_BASIS = Object.freeze({
  EXPLICIT: 'EXPLICIT_SOURCE_EVIDENCE',
  TYPE: 'INFERRED_FROM_SUPPORT_TYPE',
  UNRESOLVED: 'UNRESOLVED',
  CONFLICT: 'CONFLICTING_EXPLICIT_EVIDENCE',
});

export const RESTRAINT_PROFILE_ID = 'EXPLICIT_AND_TYPE_CLASSIFICATION_V1';
export const IDENTITY_POLICY = 'SUPPORT_IDENTITY_COMPATIBILITY_V1';
export const CANONICAL_LENGTH_UNIT = 'mm';
