import { FORMULA_IDS } from './constants.js';
import { loadError, modelError, numericalError } from './errors.js';
import { zeros, symmetryResidual, matrixScale } from './matrix.js';
import { canonicalNumber, tolerance } from './numeric.js';
import { codeUnitCompare } from './validation.js';
export function assembleMesh(model,elementEvidence){const dofOrdering=model.nodes.flatMap((node)=>[`${node.nodeId}:UX`,`${node.nodeId}:UY`]),dofIndex=new Map(dofOrdering.map((id,index)=>[id,index])),stiffness=zeros(dofOrdering.length,dofOrdering.length);elementEvidence.forEach((element)=>assembleElement(stiffness,element,dofIndex));const residual=symmetryResidual(stiffness),scale=matrixScale(stiffness),limit=tolerance(model.qualificationProfile,'stiffnessSymmetry',scale);if(residual>limit)throw numericalError('GLOBAL_STIFFNESS_SYMMETRY_FAILURE','assembly','Global stiffness symmetry did not qualify.');const boundaryEdges=buildBoundaryEdges(model.elements);return {dofOrdering,globalStiffnessMatrix:stiffness.map((row)=>row.map((value)=>canonicalNumber(value,'global stiffness'))),globalStiffnessSymmetry:{residual,scale,tolerance:limit,accepted:true},boundaryEdges,formulaIds:[FORMULA_IDS.ASSEMBLY]};}
function assembleElement(global,element,dofIndex){const indices=element.localDofOrdering.map((id)=>dofIndex.get(id));indices.forEach((row,i)=>indices.forEach((column,j)=>{global[row][column]+=element.localStiffnessMatrix[i][j];}));}
export function buildBoundaryEdges(elements){const uses=new Map();elements.forEach((element)=>triangleEdges(element).forEach((edge)=>{const key=edgeKey(edge);const rows=uses.get(key)??[];rows.push({elementId:element.elementId,edgeNodeIds:[...edge].sort(codeUnitCompare)});uses.set(key,rows);}));return [...uses.entries()].filter(([,rows])=>rows.length===1).map(([key,rows])=>({edgeKey:key,...rows[0]})).sort((a,b)=>codeUnitCompare(a.edgeKey,b.edgeKey));}
function triangleEdges(element){const [a,b,c]=element.nodeIds;return [[a,b],[b,c],[c,a]];}
export function validateBoundaryTractions(model,mesh){const boundary=new Map(mesh.boundaryEdges.map((row)=>[row.edgeKey,row]));model.loadCases.forEach((loadCase)=>loadCase.edgeTractions.forEach((traction)=>{const key=edgeKey(traction.edgeNodeIds),edge=boundary.get(key);if(!edge)throw loadError('TRACTION_EDGE_NOT_BOUNDARY',`loadCases.${loadCase.loadCaseId}.${traction.tractionId}`,'Traction edge must be a true boundary edge.');if(edge.elementId!==traction.elementId)throw modelError('TRACTION_ELEMENT_EDGE_MISMATCH',`loadCases.${loadCase.loadCaseId}.${traction.tractionId}`,'Traction edge does not belong to the declared boundary element.');}));}
export function edgeKey(ids){return [...ids].sort(codeUnitCompare).join('\0');}
