import { FORMULA_IDS } from './constants.js';
import { numericalError, singularError } from './errors.js';
import { matrixVector, zeros } from './matrix.js';
import { canonicalNumber, maxAbs, tolerance } from './numeric.js';
export function solvePartitioned(model,mesh,load){const constraints=constraintData(model,mesh.dofOrdering),free=mesh.dofOrdering.map((_,i)=>i).filter((i)=>!constraints.indexSet.has(i)),constrained=constraints.indices,k=mesh.globalStiffnessMatrix,f=load.forceVector,u=Array(k.length).fill(0);constrained.forEach((index,i)=>{u[index]=constraints.values[i];});let evidence=emptySolverEvidence();if(free.length){const kff=submatrix(k,free,free),kfc=submatrix(k,free,constrained),rhs=free.map((index,row)=>canonicalNumber(f[index]-dotRow(kfc[row],constraints.values),'partition rhs'));const solved=choleskySolve(kff,rhs,model.qualificationProfile);free.forEach((index,i)=>{u[index]=solved.solution[i];});evidence=solved.evidence;}const ku=matrixVector(k,u),residual=ku.map((value,index)=>canonicalNumber(value-f[index],'equilibrium residual')),qualification=qualifyResiduals(model,mesh.dofOrdering,free,constrained,f,residual);return {displacementVector:u.map((value)=>canonicalNumber(value,'displacement')),reactionVector:residual,freeDofIdentities:free.map((i)=>mesh.dofOrdering[i]),constrainedDofIdentities:constrained.map((i)=>mesh.dofOrdering[i]),freeDofResiduals:free.map((i)=>({dofIdentity:mesh.dofOrdering[i],value:residual[i]})),reactions:constrained.map((i)=>({dofIdentity:mesh.dofOrdering[i],value:residual[i],prescribedDisplacement:u[i]})),solverEvidence:evidence,equilibrium:qualification,formulaIds:[FORMULA_IDS.PARTITION,FORMULA_IDS.CHOLESKY,FORMULA_IDS.REACTION,FORMULA_IDS.EQUILIBRIUM]};}
function constraintData(model,dofs){const index=new Map(dofs.map((id,i)=>[id,i])),rows=model.constraints.map((row)=>({index:index.get(`${row.nodeId}:${row.dof}`),value:row.value})).sort((a,b)=>a.index-b.index);return {indices:rows.map((row)=>row.index),values:rows.map((row)=>row.value),indexSet:new Set(rows.map((row)=>row.index))};}
function submatrix(matrix,rows,columns){return rows.map((row)=>columns.map((column)=>matrix[row][column]));}
function dotRow(row,vector){return row.reduce((sum,value,index)=>sum+value*vector[index],0);}
function choleskySolve(matrix,rhs,profile){const size=matrix.length,l=zeros(size,size),scale=Math.max(1,...matrix.map((row,i)=>Math.abs(row[i]))),limit=tolerance(profile,'choleskyPivot',scale),pivots=[];for(let i=0;i<size;i+=1){for(let j=0;j<=i;j+=1){let value=matrix[i][j];for(let k=0;k<j;k+=1)value-=l[i][k]*l[j][k];if(i===j){if(value< -limit)throw singularError('INDEFINITE_FREE_STIFFNESS','solver',`Negative Cholesky pivot ${value}.`);if(value<=limit)throw singularError('UNDER_CONSTRAINED_OR_SINGULAR_SYSTEM','solver',`Cholesky pivot ${value} does not exceed ${limit}.`);l[i][j]=Math.sqrt(value);pivots.push(value);}else l[i][j]=value/l[j][j];}}const y=forward(l,rhs),solution=backward(l,y),minimum=Math.min(...pivots),maximum=Math.max(...pivots);return {solution:solution.map((value)=>canonicalNumber(value,'solved displacement')),evidence:{method:'DETERMINISTIC_CHOLESKY',pivotScale:scale,pivotTolerance:limit,pivots:pivots.map((value)=>canonicalNumber(value,'pivot')),minimumPivot:canonicalNumber(minimum),maximumPivot:canonicalNumber(maximum),pivotRatio:canonicalNumber(minimum/maximum),accepted:true}};}
function forward(l,rhs){const out=Array(rhs.length).fill(0);for(let i=0;i<rhs.length;i+=1){let value=rhs[i];for(let j=0;j<i;j+=1)value-=l[i][j]*out[j];out[i]=value/l[i][i];}return out;}
function backward(l,rhs){const out=Array(rhs.length).fill(0);for(let i=rhs.length-1;i>=0;i-=1){let value=rhs[i];for(let j=i+1;j<rhs.length;j+=1)value-=l[j][i]*out[j];out[i]=value/l[i][i];}return out;}
function qualifyResiduals(model,dofs,free,constrained,force,residual){const scale=Math.max(1,maxAbs(force),maxAbs(residual)),freeLimit=tolerance(model.qualificationProfile,'freeDofResidual',scale),freeMaximum=Math.max(0,...free.map((i)=>Math.abs(residual[i])));if(freeMaximum>freeLimit)throw numericalError('FREE_DOF_RESIDUAL_FAILURE','solver','Free-DOF residual did not qualify.');const totals={UX:0,UY:0};force.forEach((value,index)=>{totals[dofs[index].endsWith(':UX')?'UX':'UY']+=value;});constrained.forEach((index)=>{totals[dofs[index].endsWith(':UX')?'UX':'UY']+=residual[index];});const equilibriumLimit=tolerance(model.qualificationProfile,'reactionEquilibrium',scale),maximum=Math.max(Math.abs(totals.UX),Math.abs(totals.UY));if(maximum>equilibriumLimit)throw numericalError('REACTION_EQUILIBRIUM_FAILURE','solver','Reaction equilibrium did not qualify.');return {residualScale:scale,freeDofMaximumResidual:canonicalNumber(freeMaximum),freeDofTolerance:freeLimit,reactionPlusAppliedForce:{x:canonicalNumber(totals.UX),y:canonicalNumber(totals.UY)},reactionEquilibriumTolerance:equilibriumLimit,accepted:true};}
function emptySolverEvidence(){return {method:'FULLY_CONSTRAINED_NO_FREE_SOLVE',pivotScale:null,pivotTolerance:null,pivots:[],minimumPivot:null,maximumPivot:null,pivotRatio:null,accepted:true};}
