import {
  AlertTriangle,
  Boxes,
  Calculator,
  CheckSquare,
  Cylinder,
  Database,
  FileJson,
  FileText,
  FlaskConical,
  Gauge,
  GitBranch,
  Layers,
  LineChart,
  Move3D,
  PackageOpen,
  Ruler,
  Settings,
  ShieldAlert,
  Thermometer,
  Wrench,
  Zap
} from 'lucide-react';

export const ENGINEERING_ICON_REGISTRY = {
  '2d-simplified': Calculator,
  '3d-guided-cantilever': Layers,
  'pipe-rack': Cylinder,
  'calc-extended': Wrench,
  benchmarks: CheckSquare,
  'mock-loader': PackageOpen,
  'cantilever-end-load': Ruler,
  'distributed-load': LineChart,
  'thermal-growth': Thermometer,
  'point-load': Zap,
  'pipe-section': Cylinder,
  'guided-cantilever': Layers,
  'stress-combine': Boxes,
  '3d-route': Move3D,
  'short-drop': GitBranch,
  'short-drop-filter': GitBranch,
  'vertical-leg': GitBranch,
  'global-reaction': Gauge,
  nozzle: FlaskConical,
  'mist-nozzle': FlaskConical,
  flange: Database,
  'koves-flange': Database,
  'rack-loop': Cylinder,
  'rack-line': LineChart,
  friction: Gauge,
  vessel: ShieldAlert,
  'report-json': FileJson,
  'report-md': FileText,
  'report-warning': AlertTriangle,
  'pipe-data': Database,
  'material-data': Database,
  'status-proof': ShieldAlert,
  'mock-proof': CheckSquare,
  'mock-load': PackageOpen,
  fallback: Calculator
};

export function getEngineeringIcon(iconId) {
  return ENGINEERING_ICON_REGISTRY[iconId] || ENGINEERING_ICON_REGISTRY.fallback;
}
