/**
 * MODULE_REGISTRY
 * Defines the final module architecture for the Simplified Analysis app.
 *
 * Status Types: ACTIVE, REFERENCE, REMOVED
 * Engineering Levels: SCREENING, DESIGN_AID, REFERENCE, DATA_INTERFACE, UNKNOWN
 */

export const MODULE_REGISTRY = [
  {
    id: 'core-geometry',
    displayName: 'Canonical Geometry',
    path: 'src/core/geometry',
    status: 'ACTIVE',
    engineeringLevel: 'DATA_INTERFACE',
    inputModel: 'Any',
    outputTypes: ['CanonicalGeometry'],
    ownerTab: 'Geometry',
    benchmarkRequired: false,
    reportExport: false,
    replacementFor: null,
    forbiddenPaths: [],
    notes: 'Canonical geometry backbone',
  },
  {
    id: 'pcf-interface',
    displayName: 'PCF Import/Export',
    path: 'src/pcf',
    status: 'ACTIVE',
    engineeringLevel: 'DATA_INTERFACE',
    inputModel: 'PCF',
    outputTypes: ['CanonicalGeometry'],
    ownerTab: 'PCF Import',
    benchmarkRequired: true,
    reportExport: false,
    replacementFor: null,
    forbiddenPaths: [],
    notes: 'Data interface layer',
  },
  {
    id: '2d-simplified-stress-check',
    displayName: '2D Simplified Stress Check',
    path: 'src/calc-extended',
    status: 'ACTIVE',
    engineeringLevel: 'SCREENING',
    inputModel: 'CanonicalGeometry',
    outputTypes: ['2DResults'],
    ownerTab: '2D Simplified Stress Check',
    benchmarkRequired: true,
    reportExport: true,
    replacementFor: 'simp-analysis',
    forbiddenPaths: [],
    notes: 'Screening module',
  },
  {
    id: '3d-guided-cantilever',
    displayName: '3D Guided Cantilever',
    path: 'src/3d-analysis',
    status: 'ACTIVE',
    engineeringLevel: 'SCREENING',
    inputModel: 'CanonicalGeometry',
    outputTypes: ['3DResults'],
    ownerTab: '3D Guided Cantilever',
    benchmarkRequired: true,
    reportExport: true,
    replacementFor: 'gc3d',
    forbiddenPaths: ['src/3d-analysis/ExtendedSolver.js'],
    notes: 'Screening module',
  },
  {
    id: 'piperack-expansion-loop',
    displayName: 'Pipe Rack & Expansion Loop',
    path: 'src/piperack',
    status: 'ACTIVE',
    engineeringLevel: 'DESIGN_AID',
    inputModel: 'CanonicalGeometry',
    outputTypes: ['PipeRackResults'],
    ownerTab: 'Pipe Rack & Expansion Loop',
    benchmarkRequired: true,
    reportExport: true,
    replacementFor: 'adv-piperack',
    forbiddenPaths: [],
    notes: 'Design aid + screening module',
  },
  {
    id: 'reporting',
    displayName: 'Reporting',
    path: 'src/reporting',
    status: 'ACTIVE',
    engineeringLevel: 'DATA_INTERFACE',
    inputModel: 'Results',
    outputTypes: ['HTML', 'JSON'],
    ownerTab: 'Reports',
    benchmarkRequired: false,
    reportExport: false,
    replacementFor: null,
    forbiddenPaths: [],
    notes: 'Engineering report export',
  },
  {
    id: 'benchmark-validation',
    displayName: 'Benchmark/Validation',
    path: 'benchmarks',
    status: 'ACTIVE',
    engineeringLevel: 'DATA_INTERFACE',
    inputModel: 'Fixtures',
    outputTypes: ['Reports'],
    ownerTab: 'Benchmarks / Validation',
    benchmarkRequired: false,
    reportExport: false,
    replacementFor: null,
    forbiddenPaths: [],
    notes: 'Numeric QA and regression',
  },
  {
    id: 'settings-defaults',
    displayName: 'Settings/Defaults',
    path: 'src/settings',
    status: 'ACTIVE',
    engineeringLevel: 'DATA_INTERFACE',
    inputModel: 'None',
    outputTypes: ['Config'],
    ownerTab: 'Settings / Defaults',
    benchmarkRequired: false,
    reportExport: false,
    replacementFor: null,
    forbiddenPaths: [],
    notes: 'App configuration',
  },
  {
    id: 'spl2-bundle',
    displayName: 'SPL2 Bundle',
    path: 'src/spl2-bundle',
    status: 'REFERENCE',
    engineeringLevel: 'REFERENCE',
    inputModel: 'Legacy',
    outputTypes: ['LegacyResults'],
    ownerTab: null,
    benchmarkRequired: false,
    reportExport: false,
    replacementFor: null,
    forbiddenPaths: [],
    notes: 'Legacy reference / benchmark only',
  },
  {
    id: 'gc3d-legacy',
    displayName: 'Legacy GC3D',
    path: 'src/gc3d',
    status: 'REMOVED',
    engineeringLevel: 'UNKNOWN',
    inputModel: 'Legacy',
    outputTypes: ['Legacy'],
    ownerTab: null,
    benchmarkRequired: false,
    reportExport: false,
    replacementFor: '3d-guided-cantilever',
    forbiddenPaths: ['src/gc3d'],
    notes: 'Removed in previous phase',
  },
  {
    id: 'adv-piperack-legacy',
    displayName: 'Legacy Adv Pipe Rack',
    path: 'src/calc-extended/adv-piperack',
    status: 'REMOVED',
    engineeringLevel: 'UNKNOWN',
    inputModel: 'Legacy',
    outputTypes: ['Legacy'],
    ownerTab: null,
    benchmarkRequired: false,
    reportExport: false,
    replacementFor: 'piperack-expansion-loop',
    forbiddenPaths: ['src/calc-extended/adv-piperack'],
    notes: 'Removed duplicate module',
  },
  {
    id: 'simp-analysis-legacy',
    displayName: 'Legacy Simp Analysis',
    path: 'src/simp-analysis',
    status: 'REMOVED',
    engineeringLevel: 'UNKNOWN',
    inputModel: 'Legacy',
    outputTypes: ['Legacy'],
    ownerTab: null,
    benchmarkRequired: false,
    reportExport: false,
    replacementFor: '2d-simplified-stress-check',
    forbiddenPaths: ['src/simp-analysis'],
    notes: 'Old product surface',
  },
  {
    id: 'extended-solver-legacy',
    displayName: 'Legacy Extended Solver',
    path: 'src/3d-analysis/ExtendedSolver.js',
    status: 'REMOVED',
    engineeringLevel: 'UNKNOWN',
    inputModel: 'Legacy',
    outputTypes: ['Legacy'],
    ownerTab: null,
    benchmarkRequired: false,
    reportExport: false,
    replacementFor: '3d-guided-cantilever',
    forbiddenPaths: ['src/3d-analysis/ExtendedSolver.js'],
    notes: 'Removed logic file',
  }
];
