export const MODULE_STATUS = {
  ACTIVE: 'ACTIVE',
  REFERENCE: 'REFERENCE',
  REMOVED: 'REMOVED',
};

export const ENGINEERING_LEVEL = {
  SCREENING: 'SCREENING',
  DESIGN_AID_SCREENING: 'DESIGN_AID_SCREENING',
  REFERENCE: 'REFERENCE',
  DATA_INTERFACE: 'DATA_INTERFACE',
  SYSTEM: 'SYSTEM',
  UNKNOWN: 'UNKNOWN',
};

export const MODULE_REGISTRY = [
  {
    id: 'core-geometry',
    displayName: 'Canonical Geometry',
    path: 'src/core/geometry',
    status: MODULE_STATUS.ACTIVE,
    engineeringLevel: ENGINEERING_LEVEL.SYSTEM,
    inputModel: 'Any',
    outputTypes: ['CanonicalGeometry'],
    ownerTab: null,
    benchmarkRequired: true,
    reportExport: false,
    replacementFor: null,
    forbiddenPaths: [],
    notes: 'Canonical geometry backbone'
  },
  {
    id: 'pcf-interface',
    displayName: 'PCF Import/Export',
    path: 'src/pcf',
    status: MODULE_STATUS.ACTIVE,
    engineeringLevel: ENGINEERING_LEVEL.DATA_INTERFACE,
    inputModel: 'PCF File',
    outputTypes: ['CanonicalGeometry', 'Diagnostics'],
    ownerTab: 'PCF Import',
    benchmarkRequired: true,
    reportExport: false,
    replacementFor: null,
    forbiddenPaths: [],
    notes: 'PCF import/export layer data interface'
  },
  {
    id: '2d-simplified-stress-check',
    displayName: '2D Simplified Stress Check',
    path: 'src/calc-extended',
    status: MODULE_STATUS.ACTIVE,
    engineeringLevel: ENGINEERING_LEVEL.SCREENING,
    inputModel: 'CanonicalGeometry',
    outputTypes: ['CalculationResult'],
    ownerTab: '2D Simplified Stress Check',
    benchmarkRequired: true,
    reportExport: true,
    replacementFor: 'simp-analysis-legacy',
    forbiddenPaths: [],
    notes: 'Screening module for 2D simplified checks'
  },
  {
    id: '3d-guided-cantilever',
    displayName: '3D Guided Cantilever',
    path: 'src/3d-analysis',
    status: MODULE_STATUS.ACTIVE,
    engineeringLevel: ENGINEERING_LEVEL.SCREENING,
    inputModel: 'CanonicalGeometry',
    outputTypes: ['CalculationResult'],
    ownerTab: '3D Guided Cantilever',
    benchmarkRequired: true,
    reportExport: true,
    replacementFor: 'gc3d',
    forbiddenPaths: ['src/3d-analysis/ExtendedSolver.js'],
    notes: 'Screening module for 3D guided cantilever'
  },
  {
    id: 'piperack-expansion-loop',
    displayName: 'Pipe Rack & Expansion Loop',
    path: 'src/piperack',
    status: MODULE_STATUS.ACTIVE,
    engineeringLevel: ENGINEERING_LEVEL.DESIGN_AID_SCREENING,
    inputModel: 'CanonicalGeometry',
    outputTypes: ['CalculationResult', 'LayoutResult'],
    ownerTab: 'Pipe Rack & Expansion Loop',
    benchmarkRequired: true,
    reportExport: true,
    replacementFor: 'adv-piperack',
    forbiddenPaths: [],
    notes: 'Design aid + screening module'
  },
  {
    id: 'reporting',
    displayName: 'Reporting',
    path: 'src/reporting',
    status: MODULE_STATUS.ACTIVE,
    engineeringLevel: ENGINEERING_LEVEL.SYSTEM,
    inputModel: 'CalculationResult',
    outputTypes: ['HTML', 'JSON', 'Markdown'],
    ownerTab: 'Reports',
    benchmarkRequired: true,
    reportExport: false,
    replacementFor: null,
    forbiddenPaths: [],
    notes: 'Engineering report export'
  },
  {
    id: 'benchmark-validation',
    displayName: 'Benchmark/Validation',
    path: 'src/benchmarking',
    status: MODULE_STATUS.ACTIVE,
    engineeringLevel: ENGINEERING_LEVEL.SYSTEM,
    inputModel: 'BenchmarkFixture',
    outputTypes: ['BenchmarkReport'],
    ownerTab: 'Benchmarks / Validation',
    benchmarkRequired: false,
    reportExport: false,
    replacementFor: null,
    forbiddenPaths: [],
    notes: 'Numeric QA and regression'
  },
  {
    id: 'settings-defaults',
    displayName: 'Settings/Defaults',
    path: 'src/settings',
    status: MODULE_STATUS.ACTIVE,
    engineeringLevel: ENGINEERING_LEVEL.SYSTEM,
    inputModel: null,
    outputTypes: ['Settings'],
    ownerTab: 'Settings / Defaults',
    benchmarkRequired: false,
    reportExport: false,
    replacementFor: null,
    forbiddenPaths: [],
    notes: 'App configuration'
  },
  {
    id: 'spl2-bundle',
    displayName: 'SPL2 Bundle',
    path: 'src/spl2-bundle',
    status: MODULE_STATUS.REFERENCE,
    engineeringLevel: ENGINEERING_LEVEL.REFERENCE,
    inputModel: 'Legacy',
    outputTypes: ['LegacyResult'],
    ownerTab: 'Benchmarks / Reference',
    benchmarkRequired: false,
    reportExport: false,
    replacementFor: null,
    forbiddenPaths: [],
    notes: 'Legacy reference / benchmark only'
  }
];
