export const PIPE_SOLVER_SOURCE_SCHEMA = 'pipe-solver-consumer-source/v1';
export const PIPE_SOLVER_REVIEW_MODEL_SCHEMA = 'pipe-solver-review-model/v1';
export const PIPE_SCREENING_ANALYSIS_TYPE = 'pipe-screening';
export const PIPE_SCREENING_RESULT_SCHEMA = 'solver-result-contract-v1';
export const PIPE_SCREENING_RESULT_MODULE_ID = 'simplified-2d';
export const PIPE_SCREENING_ENGINEERING_LEVEL = 'BENCHMARKED_SCREENING';
export const PIPE_SCREENING_METHOD_ID = 'SIMPLIFIED_2D_TOPOLOGY_SCREENING';
export const PIPE_SOLVER_CLAIM_POLICY = 'EXISTING_BENCHMARKED_SIMPLIFIED_2D_SCREENING_ONLY';

export const PIPE_SCREENING_RESULT_METHOD_BY_GEOMETRY = Object.freeze({
  EMPTY: 'SIMPLIFIED_2D_EMPTY',
  L_SHAPE: 'SIMPLIFIED_2D_L_SHAPE',
  LOOP_OR_MULTI_LEG: 'SIMPLIFIED_2D_LOOP_OR_MULTI_LEG',
  MULTI_LEG: 'SIMPLIFIED_2D_EMPTY',
  OFFSET: 'SIMPLIFIED_2D_OFFSET',
  SINGLE_LEG: 'SIMPLIFIED_2D_SINGLE_LEG',
  STRAIGHT_RUN: 'SIMPLIFIED_2D_STRAIGHT_RUN',
  Z_SHAPE: 'SIMPLIFIED_2D_Z_SHAPE',
});

export const PIPE_SCREENING_RESULT_METHOD_IDS = Object.freeze([
  ...new Set(Object.values(PIPE_SCREENING_RESULT_METHOD_BY_GEOMETRY)),
].sort((left, right) => left.localeCompare(right)));

export const PIPE_SOLVER_ACTIONS = Object.freeze({
  OPEN_SESSION: 'OPEN_PIPE_SCREENING_SESSION',
  UPDATE_OVERRIDE: 'UPDATE_PIPE_SCREENING_OVERRIDE',
  RESET_SESSION: 'RESET_PIPE_SCREENING_SESSION',
  RUN_SCREENING: 'RUN_PIPE_SCREENING',
  CLOSE_SESSION: 'CLOSE_PIPE_SCREENING_SESSION',
  SELECT_LEDGER_ENTRY: 'SELECT_ANALYSIS_LEDGER_ENTRY',
  EXPORT_LEDGER: 'EXPORT_ANALYSIS_LEDGER',
});

export const PIPE_SOLVER_DIAGNOSTIC_CODES = Object.freeze({
  NO_SELECTION: 'PIPE_SOLVER_NO_SELECTION',
  INSPECTION_UNAVAILABLE: 'PIPE_SOLVER_INSPECTION_UNAVAILABLE',
  SESSION_ANALYSIS_MISMATCH: 'PIPE_SOLVER_SESSION_ANALYSIS_MISMATCH',
  SESSION_DATASET_MISMATCH: 'PIPE_SOLVER_SESSION_DATASET_MISMATCH',
  SESSION_TARGET_MISMATCH: 'PIPE_SOLVER_SESSION_TARGET_MISMATCH',
  SESSION_CONTEXT_STALE: 'PIPE_SOLVER_SESSION_CONTEXT_STALE',
  LEDGER_ENTRY_INVALID: 'PIPE_SOLVER_LEDGER_ENTRY_INVALID',
  LEDGER_ANALYSIS_FILTERED: 'PIPE_SOLVER_LEDGER_ANALYSIS_FILTERED',
  LEDGER_DATASET_FILTERED: 'PIPE_SOLVER_LEDGER_DATASET_FILTERED',
  LEDGER_DUPLICATE_SEQUENCE: 'PIPE_SOLVER_LEDGER_DUPLICATE_SEQUENCE',
  ACTIVE_LEDGER_FILTERED: 'PIPE_SOLVER_ACTIVE_LEDGER_FILTERED',
  CURRENT_RESULT_INVALID: 'PIPE_SOLVER_CURRENT_RESULT_INVALID',
  LEDGER_RESULT_INVALID: 'PIPE_SOLVER_LEDGER_RESULT_INVALID',
  SESSION_FAILED: 'PIPE_SOLVER_SESSION_FAILED',
});

export const PIPE_SOLVER_LIMITATIONS = Object.freeze([
  'Benchmarked simplified 2D screening only.',
  'Not final piping-code stress analysis.',
  'Not general 3D piping flexibility.',
  'No branch flexibility, equipment interaction, nonlinear gaps, friction, or restraint stiffness.',
  'No automatic execution.',
  'Inputs must be explicit or user-overridden through the existing session boundary.',
]);

export const PIPE_SOLVER_EXPORT_FORMATS = Object.freeze(['json', 'csv', 'markdown']);
